apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: afrikfid
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - api.yaml
  - web.yaml
  - ingress.yaml
  - monitoring/prometheus.yaml
  - monitoring/grafana.yaml
